### ISSUE TITLE
Reactor thread crash with "Bad file number"

### ISSUE THREAD

**Issue by jothan** [smol-rs/async-io#198]
I can trigger a panic in the reactor thread by refreshing a page quickly with the hyper HTTP server that is running over async-io-mini (ESP32, ESP-IDF std config).

My guess would be that a closed file descriptor is added to the select() call.

Panic message:
```
thread 'async-io-mini' panicked at async-io-mini-e233321a2e3791f3/b28e2c7/src/reactor.rs:336:28:
called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file number" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

abort() was called at PC 0x401553c2 on core 0
0x401553c2 - panic_abort::__rust_start_panic::abort
    at /home/joe/.rustup/toolchains/esp/lib/rustlib/src/rust/library/panic_abort/src/lib.rs:49
```

**Comment by jothan** [comment]
I reported this on the wrong repo, it should have been async-io-mini. Sorry for the noise.

https://github.com/ivmarkov/async-io-mini/issues/2
